on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - '*'

name: Running Tests

jobs:
  test_integration:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Localstack
        run: make localstack

      - name: Create a docker image
        run: make docker

      - name: Run Tests
        run: ./run-tests.sh
        working-directory: ./tests
