on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - '*'

name: Static Analysis

jobs:
  golangci:
    name: Golang
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.42.1
          args: --config .github/golangci.yml
